name: "Another Markup Language"
version: "0.1.4a"
description: "A transpiler for AML to HTML."
information: ""

authors:
    - survari

products:
    - ./od/aml.jar: "/usr/bin/AML.jar"
	  - ./aml: "/usr/bin/aml"
